# Generated by Django 4.1.1 on 2022-10-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('assessment_name', models.CharField(max_length=300, null=True)),
                ('question', models.CharField(max_length=300, null=True)),
                ('videoAns', models.FileField(blank=True, upload_to='media')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
